### ISSUE TITLE
Get MIDI files of model outputs

### ISSUE THREAD

**Issue by kayoyin** [omarperacha/TonicNet#2]
Great work! I was wondering if you can include an explanation how to retrieve the MIDI files from the model predictions. Is that something you can do in this repo?

Thanks a lot!

**Comment by omarperacha** [comment]
Sure, after running `python main.py --sample`, the MIDI version of the generated sample will be automatically saved to ` ./eval/sample.mid`, and a "rhythmically smoothed" post-processed version will be saved to `./eval/sample_smoothed.mid`. The smoothed version is the more natural-sounding one.

For anyone looking for high quality synthetic Bach Chorales in MIDI form, I'd recommend the [JS Fake Chorales](https://github.com/omarperacha/js-fakes) which are made from my newer algorithm. There's even a [web app](https://omarperacha.github.io/make-js-fake/) which allows you to generate more MIDI files from scratch.
